(function(){
'use strict';
const NS=window.SeaBirds=window.SeaBirds||{},Core=NS.Core;
let deviceFilters=new Set();
const source=d=>{if(!d.computer&&!d.computerModel&&!String(d.id||'').startsWith('shearwater-'))return'Manual entry';const raw=String(d.computer||d.computerModel||'Shearwater').replace(/^Shearwater\s+/i,'').trim(),known={'perdix':'Perdix','perdix ai':'Perdix AI','perdix 2':'Perdix 2','teric':'Teric','petrel 2':'Petrel 2','petrel 3':'Petrel 3','nerd 2':'NERD 2','peregrine':'Peregrine','tern':'Tern'};return known[raw.toLowerCase()]||raw||'Shearwater'};
function rows(target,dives){if(!target)return;const state=Core.getState();target.innerHTML=dives.length?dives.map(d=>{const date=Core.formatDate(d.date),subtitle=d.location||d.buddy||'',mode=d.diveMode||((d.profile||[]).some(point=>point.setpoint!=null)?'CCR':'OC'),style=d.diveStyle||'';return`<button class="dive-row" data-id="${Core.esc(d.id)}"><span class="dive-number-cell"><small>Dive #</small><b>${d.diveNumber??'—'}</b></span><span class="date-tile full-date"><b>${date.ymd}</b></span><span class="site"><span class="dive-title-line"><em>${Core.esc(mode)}</em><b>${Core.esc(d.site)}</b>${style?`<em>${Core.esc(style)}</em>`:'<i></i>'}</span>${subtitle?`<small>${Core.esc(subtitle)}</small>`:''}</span><span class="metric"><b>${Core.converted(+d.depth).toFixed(1)} ${state.settings.depth}</b></span><span class="metric"><b>${d.duration} min</b></span><span class="metric"><b>${d.temp==null?'—':Core.temperature(+d.temp).toFixed(0)+'°'+state.settings.temp.toUpperCase()}</b></span><span>›</span></button>`}).join(''):'<div class="empty"><b>No dives yet</b>Connect your Shearwater or add a dive manually.</div>'}
function sources(){return[...new Set(Core.getState().dives.map(source))].sort((a,b)=>a==='Manual entry'?1:b==='Manual entry'?-1:a.localeCompare(b))}
function renderFilters(){const target=document.getElementById('deviceFilters');if(!target)return;const available=sources(),valid=new Set(available);deviceFilters=new Set([...deviceFilters].filter(item=>valid.has(item)));target.innerHTML=`<span>Show:</span><label><input type="checkbox" data-device-filter="all" ${deviceFilters.size?'':'checked'}> All</label>${available.map(item=>`<label><input type="checkbox" data-device-filter="${Core.esc(item)}" ${deviceFilters.has(item)?'checked':''}> ${Core.esc(item)}</label>`).join('')}`}
function filterRows(){const state=Core.getState();let dives=[...state.dives],q=(document.getElementById('search')?.value||'').toLowerCase(),sort=document.getElementById('sort')?.value;if(q)dives=dives.filter(d=>JSON.stringify(d).toLowerCase().includes(q));if(deviceFilters.size)dives=dives.filter(d=>deviceFilters.has(source(d)));dives.sort(sort==='date-asc'?(a,b)=>a.date.localeCompare(b.date):sort==='depth-desc'?(a,b)=>b.depth-a.depth:(a,b)=>b.date.localeCompare(a.date));rows(document.getElementById('allDives'),dives)}
function render(){const state=Core.getState(),dives=[...state.dives].sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('diveCount').textContent=dives.length;document.getElementById('statDives').textContent=dives.length;const mins=dives.reduce((n,d)=>n+(+d.duration||0),0);document.getElementById('statTime').innerHTML=(mins/60).toFixed(mins>=600?0:1)+'<sup>h</sup>';const depth=Math.max(0,...dives.map(d=>+d.depth||0));document.getElementById('statDepth').textContent=dives.length?Core.converted(depth).toFixed(1)+' '+state.settings.depth:'—';const longest=Math.round(Math.max(0,...dives.map(d=>+d.duration||0))),hours=Math.floor(longest/60),remainder=longest%60;document.getElementById('statLongest').textContent=dives.length?(hours?`${hours}h ${remainder}min`:`${remainder}min`):'—';rows(document.getElementById('recentDives'),dives.slice(0,4));renderFilters();filterRows()}
function init(){Core.registerRenderer(render);document.getElementById('search').oninput=filterRows;document.getElementById('sort').onchange=filterRows;document.getElementById('deviceFilters').onchange=event=>{const input=event.target.closest('[data-device-filter]');if(!input)return;if(input.dataset.deviceFilter==='all')deviceFilters.clear();else input.checked?deviceFilters.add(input.dataset.deviceFilter):deviceFilters.delete(input.dataset.deviceFilter);renderFilters();filterRows()};document.addEventListener('click',event=>{const row=event.target.closest('.dive-row');if(row)Core.feature('diveEditor')?.open(row.dataset.id)})}
Core.registerFeature('diveList',{init,render,filterRows,source});
})();
